### ISSUE TITLE
Gretel-trails stores

### ISSUE THREAD

**Issue by ahuth** [lassebunk/gretel-trails#1]
Hi,
Would it be possible to make a new store that uses instance variables to store the trail?

If it is, would that be something you'd be interested in pulling in if I worked on it?

Thanks,
Andrew

**Comment by lassebunk** [comment]
Hi Andrew,

Yes, that would be very nice.
Could you explain little further what you were planning to do?

Thanks,
Lasse

søndag den 12. januar 2014 skrev Andrew :

**Comment by ahuth** [comment]
Sure.

Forgive me if my understanding of how the gem works is wrong. It looks like it's set up in a **really** modular way that would make it relatively easy to add different types of stores.

I'm thinking about implementing a store that saves the encoded array in an instance variable, instead of in the url, database, or whatever.

My understanding is I could make a store (subclass of Store) that implements the save, retrieve, delete_expired, key_count, and delete_all_keys methods. My plan would be for the subclass to have an array or hash that would store the trail information.

Of course, you would know better than me if this is viable. Do you think it would work?

-Andrew

**Comment by lassebunk** [comment]
Ok, just wondering how you’d persist the trails between requests then?

On 12 Jan 2014 at 20:18:15, Andrew (notifications@github.com) wrote:

Sure.

Forgive me if my understanding of how the gem works is wrong. It looks like it's set up in a really modular way that would make it relatively easy to add different types of stores.

I'm thinking about implementing a store that saves the encoded array in an instance variable, instead of in the url, database, or whatever.

My understanding is I could make a store (subclass of Store) that implements the save, retrieve, delete_expired, key_count, and delete_all_keys methods. My plan would be for the subclass to have an array or hash that would store the trail information.

Of course, you would know better than me if this is viable. Do you think it would work?

-Andrew

**Comment by ahuth** [comment]
I really have no idea.

I'll mess around with it. If I figure something out, I'll get back to you. If not, no harm done.

Take care.
